version: '2'

services:  
    utils-services:
        container_name: utils-services
        image: utils-services:master
        working_dir: /var/www/html/
        environment:
            - NODE_ENV=production
            - PORT=3000
            - ALLOWED_ORIGINS=jbehuet.github.io,kihon.fr,www.kihone.fr
        env_file:
            - /var/www/utils-services/production.env
        volumes:
            - /data/nedb:/var/www/html/db/
        ports:
            - 127.0.0.1:3001:3000