version: '2'

services:  
    utils-services:
        container_name: utils-services
        image: utils-services:master
        working_dir: /var/www/html/
        environment:
            - NODE_ENV=production
            - PORT=3000
            - ALLOWED_ORIGINS=localhost.kihon.fr,kihon.fr,www.kihon.fr
        volumes:
            - /data/nedb:/var/www/html/db/
        ports:
            - 127.0.0.1:3001:3000